# 1.1 Numpy Core Concepts

Numpy are n-dimensional arrays of values, all of the **same** datatype.

In [2]:
# It's convention to import numpy as 'np'
import numpy as np

In [3]:
# Create a 2-dimensional array from a list of lists
x = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

display(x)
display(x.dtype)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

dtype('int64')

## Accessing Elements
Arrays elements can be accessed much like lists. Indexing is zero based, and arrays can be sliced with `:` like lists can


In [5]:
# Return the first element from the first axis of the array (i.e. a row)]
x[0]

array([1, 2, 3])

In [27]:
# Return the first value in the first row with its coordinates
x[0, 0]

1

In [29]:
# Return the first two rows in the array with a slice
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# Return the last element in the last row with negative indices
x[-1, -1]

9

In [6]:
# Retun the second two elements in the first two rows.
x[:2, -2:]

array([[2, 3],
       [5, 6]])

# Modifiying Elements

In [9]:
# Assign to an element to update it's value.
x[0,0] = 5
x

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Single values are broadcast to the array
x[1] = 1 # This will set the whole second row to 1.
x

array([[5, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

In [15]:
# A slice is a view into the array, so updating it will update the array.
x[:2] = 3
x

array([[3, 3, 3],
       [3, 3, 3],
       [7, 8, 9]])

## Operations on Arrays

Most operations on numpy arrays are applied element wise.

In [32]:
# Add one to each element in the array
x + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
# Multiply each element by two.
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
# Raise each element to the power of itself.
x ** x

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [39]:
# Add two arrays of equal size
y = np.array(
    [
        [1,1,1],
        [0,0,0],
        [2,2,2]
    ]
)
x + y

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [16]:
# You cant add arrays of different sizes!
z = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)
# We expect an error here!
x + z

ValueError: operands could not be broadcast together with shapes (3,3) (2,5) 

## Aggregation

Arrays can be aggregated with fast numerical operations e.g. sum, min max etc.


In [41]:
x.sum()

45

In [45]:
# supplying an axis will sum along that direction
# axis=0 will sum the nth element of each row.
x.sum(axis=0)

array([12, 15, 18])

In [47]:
# axis=1 will sum the nth element of each column (e.g. sum values in each row)
x.sum(axis=1)

array([ 6, 15, 24])

In [49]:
x.mean()

5.0

In [91]:
# You Get the idea
x.max()

9

## Null Values
Numpy has a special datatype for null values in the form of `np.nan`. `nan` values are supported in floating point arrays and object arrays but not integers arrays.

In [101]:
y = np.array([1.0,2.0,3.0,np.nan,5.0])

In [104]:
y.sum() # adding nan to somethign returns nan so our sum will be nan

nan

In [107]:
np.nansum(y) # Numpy method for summing ignoring nans. See also nanmax() nanmin() etc

11.0